// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KinokoBJ","status":true,"description":"トランプゲーム「ブラックジャック」を実装します。\r\nカジノのお供にどや？","parameters":{"coinVariables":"1","playerName":"おしるこ","dealerName":"ヨシダ　","minRate":"100","maxRate":"1000"}}
];
